name: Build Workflow

on:
  push:
    branches:
      - master
      - development

env:
  BUILD_TYPE: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print build type
        run: echo "$BUILD_TYPE"
